"use client";
import "../../style/globals.css";
import React from "react";


import Footer from "../components/Footer";

// export const metadata = {
//   title: "მაუწყებელი • Mautskebeli",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
       

        {children}
        <Footer />
      </body>
    </html>
  );
}
