import "../../../style/globals.css"

import { MenuProvider } from "@/app/context/MenuContext";

import SportHeader from "@/app/components/SportHeader";
import SportNavigation from "@/app/components/SportNavigation";
import SportFooter from "@/app/components/SportFooter";

export const metadata = {
  title: "მაუწყებელი • Mautskebeli",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-[#AD88C6]'>
      <MenuProvider>
          <div className="sticky top-0 z-50">
           <SportHeader />
            <SportNavigation />
          </div>
        </MenuProvider>
        {children}
        <div className="mt-40 bg-[#AD88C6]">
        <SportFooter />
        </div>
       
      </body>
    </html>
  );
}