"use client";
import '../../../style/globals.css'

import Header from '@/app/components/Header';
import Navigation from '@/app/components/Navigation';

import { MenuProvider } from '@/app/context/MenuContext';
import Footer from '@/app/components/Footer';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MenuProvider>
          <div className="sticky top-0 z-50">
            <Header />
            <Navigation />
          </div>
        </MenuProvider>

        {children}
        <Footer />
      </body>
    </html>
  );
}
