import '../../style/globals.css'

import { MenuProvider } from "@/app/context/MenuContext";

import SportHeader from '../components/SportHeader';
import SportNavigation from '../components/SportNavigation';
import SportFooter from '../components/SportFooter';
import Script from 'next/script';
import AnalyticsPageView from '../components/AnalyticsPageView';

export const metadata = {
  title: "მაუწყებელი • Mautskebeli ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" href="/favicon.ico" />
      </head>
      <body className='bg-[#AD88C6]'>
      <MenuProvider>
          <div className="sticky top-0 z-50">
           <SportHeader />
            <SportNavigation />
          </div>
        </MenuProvider>
        {children}
        <div className="mt-40 bg-[#AD88C6]">
        <SportFooter />
        </div>
        
        {/* Google Analytics */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-C2ZPMYP4FY"
          strategy="afterInteractive"
        />
        <Script
          id="ga-init-all-sport-videos"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-C2ZPMYP4FY', { send_page_view: false });
            `
          }}
        />
        <AnalyticsPageView />
      </body>
    </html>
  );
}