import '../../style/globals.css'
import '../../node_modules/alk-tall-mtavruli/css/alk-tall-mtavruli.css';
import { Noto_Sans_Georgian } from '@next/font/google';

const notoSansGeorgian = Noto_Sans_Georgian({
  subsets: ['georgian'],
  display: 'swap',
  variable: '--font-noto-sans-georgian',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={notoSansGeorgian.variable}>
      <head>
        <meta property="og:url" content="https://mautskebeli-ge-4bpc.vercel.app" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Your Website Title" />
        <meta property="og:description" content="Your description" />
        <meta property="og:image" content="https://www.your-domain.com/path/image.jpg" />
      </head>
      <body>{children}</body>
    </html>
  );
}
