import { useRouter } from 'next/router';
import Head from 'next/head';
import '../../style/globals.css';
import { Noto_Sans_Georgian } from '@next/font/google';

const notoSansGeorgian = Noto_Sans_Georgian({
  subsets: ['georgian'],
  display: 'swap',
  variable: '--font-noto-sans-georgian',
});

export default function ShromaLayout({ children }) {
  const router = useRouter();
  const fullUrl = `https://mautskebeli-ge-4bpc.vercel.app${router.asPath}`;

  return (
    <html lang="en" className={notoSansGeorgian.variable}>
      <Head>
        <title>Mautskebeli</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:url" content={fullUrl} />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Mautskebeli" />
        <meta property="og:description" content="Generated by create next app" />
        {/* You can add an og:image tag later when you have an image */}
        {/* <meta property="og:image" content="https://mautskebeli-ge-4bpc.vercel.app/path/to/your/image.jpg" /> */}
      </Head>
      <body>{children}</body>
    </html>
  );
}
